// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package users

import (
	"database/sql"
)

type User struct {
	ID        int32
	Email     sql.NullString
	Password  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Age       sql.NullInt32
	Owner     sql.NullBool
}
