// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package users

import (
	"context"
	"database/sql"
)

const create = `-- name: Create :one
insert into hronos.public.users (email, password, owner)
values ($1, $2, $3)
returning email, first_name, last_name
`

type CreateParams struct {
	Email    sql.NullString
	Password sql.NullString
	Owner    sql.NullBool
}

type CreateRow struct {
	Email     sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CreateRow, error) {
	row := q.db.QueryRowContext(ctx, create, arg.Email, arg.Password, arg.Owner)
	var i CreateRow
	err := row.Scan(&i.Email, &i.FirstName, &i.LastName)
	return i, err
}

const fetchAll = `-- name: FetchAll :many
SELECT id, email, password, first_name, last_name, age, owner
FROM hronos.public.users
`

type FetchAllRow struct {
	ID        int32
	Email     sql.NullString
	Password  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Age       sql.NullInt32
	Owner     sql.NullBool
}

func (q *Queries) FetchAll(ctx context.Context) ([]FetchAllRow, error) {
	rows, err := q.db.QueryContext(ctx, fetchAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchAllRow
	for rows.Next() {
		var i FetchAllRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Password,
			&i.FirstName,
			&i.LastName,
			&i.Age,
			&i.Owner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchOne = `-- name: FetchOne :one
select id, email, password, first_name, last_name, age, owner
from hronos.public.users
where id = $1
limit 1
`

type FetchOneRow struct {
	ID        int32
	Email     sql.NullString
	Password  sql.NullString
	FirstName sql.NullString
	LastName  sql.NullString
	Age       sql.NullInt32
	Owner     sql.NullBool
}

func (q *Queries) FetchOne(ctx context.Context, id int32) (FetchOneRow, error) {
	row := q.db.QueryRowContext(ctx, fetchOne, id)
	var i FetchOneRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Password,
		&i.FirstName,
		&i.LastName,
		&i.Age,
		&i.Owner,
	)
	return i, err
}
